version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: tetkaslepoka/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - foodgram_db
  frontend:
    image: tetkaslepoka/foodgram_frontend
    env_file: ../.env
    command: cp -r /app/build/.  /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: tetkaslepoka/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/media
